swagger: "2.0"
info:
  description: "API for managing anti-burglar camera."
  version: "1.0.0"
  title: "Camera Server API"
tags:
- name: "Server"
  description: "Server for accsesing camera photos"
paths:
  /img:
    post:
      tags:
      - "Post"
      summary: "Posts a photo in binary format"
      description: "Posts a photo from camera in binary format and saves it in database. After post it send a status message."
      operationId: "Photo"
      consumes:
      - "multipart/form-data"
      produces:
      - "multipart/form-data"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Level"
      responses:
        "200":
          description: "message: image received. size={}x{}.format(img.shape[1], img.shape[0]."
          schema:
            $ref: "#/definitions/Level"
        "400":
          description: "Invalid data."
        "500":
          description: "Unexpected error."
  /img/<img_id>:
    get:
      summary: "Return level of red LED"
      description: "Returns current level od red LED."
      operationId: "getPicture"
      responses:
        "200":
          description: "Operation Successfull"
        "404":
          description: "Image {} doesn't exist.format(img_id)"
          schema:
            $ref: "#/definitions/Level"
        "500":
          description: "Unexpected error."
    delete:
      tags:
      - "delete"
      summary: "Uploads image"
      description: "Uploads image caught by night camera"
      operationId: "changeGreen"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Level"
      responses:
        "200":
          description: "Image uploaded!"
          schema:
            $ref: "#/definitions/Level"
        "400":
          description: "Image doesn't exist!"
        "500":
          description: "Unexpected error."
definitions:
  Level:
    type: "object"
    properties:
      level:
        type: "integer"
        description: "Brightness level of a color (0-100)"
