swagger: "2.0"
info:
  description: "API for managing anti-burglar camera."
  version: "1.0.0"
  title: "Camera Server API."
tags:
- name: "Server"
  description: "Server for accsesing camera photos."
paths:
  /<room_number>:
    post:
      tags:
      - "camera"
      summary: "Posts a photo in binary format."
      description: "Posts a photo from camera in binary format and saves it in database. After post it send a status message."
      operationId: "postPicture"
      consumes:
      - "multipart/form-data"
      produces:
      - "multipart/form-data"
      parameters:
      - in: formData
        name: upfile
        type: file
        required: true
        description: The picture to upload.
      responses:
        "201":
          description: "message: image received. size={}x{}.format(img.shape[1], img.shape[0]."
        "400":
          description: "Invalid data. You may entered wrong room number"
        "500":
          description: "Unexpected error."
  /<room_number>/<img_ts>:
    get:
      tags:
      - "camera"
      summary: "Return picture from database."
      description: "Returns a picture from a database filtering by timestamp and room number."
      operationId: "getPicture"
      produces:
      - "multipart/form-data"
      responses:
        "200":
          description: "Operation Successfull"
        "404":
          description: "Image {} or room {} doesn't exist.format(img_id,room_number)"
        "500":
          description: "Unexpected error."
    delete:
      tags:
      - "camera"
      summary: "Delete picture."
      description: "Deletes picture from a database  filtering by timestamp and room number."
      operationId: "deleteCamera"
      responses:
        "204":
          description: "Image deleted."
        "404":
          description: "Image {} or room {} doesn't exist.format(img_id,room_number)"
        "500":
          description: "Unexpected error."
